### ISSUE TITLE
Agree on tech stack

### ISSUE THREAD

**Issue by dupreesi** [techforbetter/myPickle#10]
We need to agree our provisional tech stack in order that our devops can start setting up our environment and package.json and we can start coding on Monday 10th Dec.

We now have an better idea of what the web app is going to be and needs to do. We agreed that SEO is a big part and favours a static page rendering framework such as Gatsby or Next (both building on React). 

Please do some research of how to set up a project integrating dynamic and static rendering. We had groups using Express-Gatsby-React stacks. In production they were using heroku as a backend provider and netlify as a frontend hosting service.  

Devops, please research and discuss the

- [x] Tech stack we should use 
- [x] Testing package we want to use (e.g. Jest)
- [x] Additional packages/middleware we will need (e.g. bodyparser...)
- [x] Any other bits we need to discuss for set up

If you are happy to start setting up the project please go ahead. Happy coding :)

**Comment by thejoefriel** [comment]
@ismail2009 @hshahwan - hey! Here's the quick guide on setting up mongodb on your computer https://docs.google.com/document/d/1W4wKkD-y53CYpveJcM8SLDib-kUDlxvI253kk5V1-kw/edit 

We'd be using Mongoose with it, which has loads of really useful functions to find and get what you need from your database. Some more info on this here: https://mongoosejs.com/docs/queries.html

In terms of file structure it is very similar to SQL. You have a database folder in your server and in here you have a db_connection.js file. Then you can have a 'models' folder (Models are basically the same as tables in SQL), and a queries folder just like usual. 

Let me know if you'd like me to post any other tutorials/explanations. 

And as we say, absolutely fine to not use it if you would prefer not to :)

**Comment by thejoefriel** [comment]
@ismail2009 @hshahwan - also, here's some information on Tachyons. 

However, I am absolutely fine not using these. If we use mongodb I don't want us to feel like we're working with too many new things, so honestly will only work with these if it is something you would want to work with too! :) 

Here's a useful explanation on why they can be useful and how to use them: https://github.com/dwyl/learn-tachyons

You can still use CSS and also use Tachyons with Styled Components. Essentially you use the [Tachyons dictionary](https://tachyons.io/docs/table-of-styles/) which will help you find any styling you want and then you can add them onto your component to style it e.g. 
```
const Button = styled.button.attrs({
className: "bw0 br2 bg-blue pv2 ph3 fw1 tc ttu tracked"
})`
color: var(--primary);
`
```
As you can see with the above example, you can apply the Tachyon styles you want via the className. In addition, you can still go ahead and add any other stylings you might like to apply as you would with Styled Components normally.

Generally, people say you need to have the Tachyons dictionary open to check the attributes, but overall it makes the code a lot more succinct and can make styling really quick once you get to grips with it. 

As I say, I am absolutely fine not to use these :) Happy for it to be something we look at as self learning outside of the project if you prefer :)

**Comment by thejoefriel** [comment]
@hshahwan @ismail2009 @dupreesi 

In terms of the rest of the tech stack:

#### Testing:
Have we agreed on which testing package we'd like to use? I have found Jest has been good, but happy to follow what people are most comfortable with. 

#### Additional packages/middleware
In terms of dependencies, I think there's a few we're likely to need (e.g. sweetalert on the client side, passport on the server side), but I think we can just install these when we need them? In terms of any others we should perhaps install now:
- server
    - mongoose (if we use MongoDB)
- client
    - axios
    - styled-components
    - react-testing-library (perhaps?)

#### Other bits:
So we've agreed to use airbnb eslint config, which means we need to make sure in our code we are:
- using single quotes
- soft tabs set to 2 spaces


Anything else we need to agree before we can close this issue?

**Comment by thejoefriel** [comment]
@hshahwan @ismail2009 Do you use Prettier to format your code?

**Comment by hshahwan** [comment]
@thejoefriel I totally agree on the tech stack, about testing, I think jest.js for react, right?
and will use super testing for back end?

**Comment by hshahwan** [comment]
> @hshahwan @ismail2009 Do you use Prettier to format your code?

yes, I used to install it on my editor.

**Comment by thejoefriel** [comment]
Cool all good re prettier :)

@hshahwan on testing, we will need a testing framework for supertest to work with. We used jest last time alongside supertest for back end, which worked nicely.

**Comment by hshahwan** [comment]
Great, so let's do it.
but this also new for me hhh :D
