### ISSUE TITLE
Set up style guide

### ISSUE THREAD

**Issue by dupreesi** [techforbetter/myPickle#11]
create a clear style guide so everyone knows what colours, sizing etc to be using.

**Comment by MyPickleCat** [comment]
[Brand guidelines 1.pdf](https://github.com/techforbetter/myPickle/files/2654003/Brand.guidelines.1.pdf)
Hoping this helps. Had viewed colours at http://coolors.co/ and fonts at 1001fonts.com

**Comment by MyPickleCat** [comment]
Hope this helps, contains colour palette from http://coolors.co/ and fonts from 1001fonts.com
[Brand guidelines 1.pptx](https://github.com/techforbetter/myPickle/files/2654011/Brand.guidelines.1.pptx)

**Comment by thejoefriel** [comment]
@hshahwan @ismail2009 @dupreesi 

Here is an outline for the styling, which can be put into the index.css once it's created. Considering the green is quite strong, I've recommended a largely monochromatic style to avoid color clashes. The green should be used sparingly as we've done in the prototype. 

Feel free to add your required changes in further comments below. :) 

### Colours:

This is working on a mainly monochromatic format using the primary colour. There are darker and lighter versions which can help for borders and variation. 

Please use secondary and alert sparingly. 

There is also a gray alongside the white and black colors to provide subtle distinctions for cards (e.g. a white background card sitting on a gray background for the screen as shown in the Figma prototype)

```
--primary: #53dd6c
--darkPrimary: #4EA95F
--lightPrimary: #91E9A1
--secondary: #f7f161
--alert: #ff0022
--white: #f0f7f4
--black: #2a2b2e
--gray: #E8EDE9
```

### Fonts

File for headertext font attached here:
[gosmick_sans.zip](https://github.com/techforbetter/myPickle/files/2663798/gosmick_sans.zip)

```
/* headerText */
h1,
h2 {
  font-family: "Gosmick Sans", sans-serif;
}

/* mainText */
@import url('https://fonts.googleapis.com/css?family=Merriweather+Sans:300,300i,400,400i,700');

body {
  font-family: 'Merriweather Sans', sans-serif;
}
```

### Sizing / Spacing
- Default 1rem should be 16px;
- Please work in rules of 8px for scaling up or down any margins, padding, font-sizes etc
