### ISSUE TITLE
Set up project environment

### ISSUE THREAD

**Issue by dupreesi** [techforbetter/myPickle#16]
- [ ] Download the dev dependencies and dependencies we definitely need for this project (e.g. express) 
- [ ] react/ gatsby/ next (?)
- [ ] Sort out git ignore file
- [ ] set up eslint rules (please not the airBnB ones :))

**Comment by arrested-developer** [comment]
My suggestion is to set up a parent repo, with two repos inside - one for the client and one for the server. The parent repo will have no dependencies, it will only have scripts that can run and build the repos inside.

The client folder can hold the React project, and the server folder can hold the Express project - each one will have it's own package.json and scripts, and the required dependencies.

Then you can deploy each part separately - the React front-end can deploy to Netlify for fast speed, and the Express server can deploy on Heroku. Using Netlify's option to pre-render for search engines, you can get the best improvement to SEO. It may also be worth investigating react-helmet to add metadata to your index.html.

For development you can use the proxy in create-react-app (or Webpack if you're not using create-react-app) to allow your React app access to the API server.

Only in deployment your API requests will need to go to the Heroku server, and you may find issues with CORS that need to be addressed. [This article](https://medium.com/queers-in-tech/deploying-a-react-app-to-heroku-50c3f7626aa5) might be helpful. 

I'm around to help if you have any questions 😊
