### ISSUE TITLE
Database Setup

### ISSUE THREAD

**Issue by dupreesi** [techforbetter/myPickle#20]
- [x] think about schema setup and relations (maybe draw a diagram (e.g. with draw.io and post it as a comment)
- [x] decide which framework (mongo or postgres)

**Comment by thejoefriel** [comment]
@dupreesi @ismail2009 @hshahwan 

Hey, here's a link to the potential layout: https://www.draw.io/#G1qNPoM8ibJsXUj8dciXLt_tdDyIYIiZXl
I've tried to future proof this to a certain extent, which means we have a number of tables but overall I think follows best practice.

Few quick things to explain my rationale:
- User table - we get the core info and contact details for that user

- Profile - every user has an initial profile created with the core info they have provided for Cat then to mark as approved

- SupportType - at the moment our two different types of profiles are for therapists and then every other type of support, but in order that this can scale (e.g. customised questions/profiles for personal trainers), we need a table that will store the support types, linking to the relevant profile and questions so we can load the right questions for that profile

- ProfileQuestions - includes crucial information like whether it is required, the questiontext, input_type (e.g. checkbox, radiobutton, text), options (in case there's options for them to select from) and also importantly category (e.g. basic info) so we know in which section to show those questions. 

- ProfileAnswers - all answers are stored here, linked to the relevant questionid and profileid so we can always relate for the right profile and order based on the question's details (e.g. input_type, category)

**Comment by thejoefriel** [comment]
[Sign-up-form-modified-for-DB.xlsx](https://github.com/techforbetter/myPickle/files/2675142/Sign-up-form-modified-for-DB.xlsx)
