### ISSUE TITLE
General File Structure

### ISSUE THREAD

**Issue by ismail2009** [techforbetter/myPickle#58]
|--Root

    | |-- Client
      | | |-- assets
      | | |-- Components
      | | | |-- Common
      | | | |-- Genaric-helpers
      | | | |-- Layout
      | | | |-- app
      | | | |-- OthersComponent
      | | |-- index.css
      | | |-- index.js
      | | |-- package.json

    | |--Server
      | | |--bin
      | | |--controllers
      | | | |-- middlewares
      | | | |-- index.js
      | | |--database
      | | | |--models
      | | | |--query
      | | | |--Build
      | | | | |-- DummyData.js
      | | | | |-- index.js // build all database
      | | | |-- dbConnection.js
      | | |--routes
      | | |--app.js

**Comment by RamyAlshurafa** [comment]
Just a little thing for files/directories naming convention, If you ask me.
make your files naming consistent:
* in react files:
  - use PascalCase for files.
 - [See this](https://reactjs.org/docs/faq-structure.html)
* in server:
  - use snake_case 
  `DummyData` => `dummy_data.js`
  `dbConnection` => `db_connection.js`
  `Build` => `build`
