### ISSUE TITLE
Initial Design

### ISSUE THREAD

**Issue by dupreesi** [techforbetter/myPickle#9]
What do you think regarding colours and font?

<img width="360" alt="bildschirmfoto 2018-12-06 um 09 10 31" src="https://user-images.githubusercontent.com/23721486/49573829-ddd3de00-f936-11e8-9538-9f32054ea083.png">

**Comment by MyPickleCat** [comment]
@dupreesi Looks super neat. 

Colours: For Login button - can we make it similar to the github comment box i.e. shaded, outline & white font?

Font: Find it a bit difficult to read - kinda looks like My Dickle 😨 can you check out the Gosmicksans from 1001fonts and find something similar? If this is Gosmicksans then we'll need to find something a bit clearer, but still 'friendly' and not too formal.

**Comment by thejoefriel** [comment]
Hey @MyPickleCat thanks so much for your time right now! I'm cracking on with the revised design prototype now:

In terms of circular design for the 7 points of integrated wellness, I love this sort of design:
https://99designs-blog.imgix.net/wp-content/uploads/2018/07/attachment_35014419-e1531140189739.jpg?auto=format&q=60&fit=max&w=930

😄 What do you think?

**Comment by MyPickleCat** [comment]
😍  beautiful!
Eight areas of wellness now... hopefully that design still works?!

Emotional, 
Social, 
Physical, 
Financial, 
Occupational, 
Intellectual, 
Environmental, 
Spritual.

**Comment by MyPickleCat** [comment]
@thejoefriel and you can be in more than one section. 
I'd like to develop further after prototype that you can rank these areas. E.g. my services primarily addresses emotional wellness, but also offers social wellness - this way more 'score/match weighting' is given to emotional wellness. 
If a user was searching for emotional wellness, the above service would be shown in the listings above another service that ranks their number 1 priority as social wellness, followed by emotional wellness second. 
Think this is too sophisticated for prototype but tell me if I'm wrong!

**Comment by thejoefriel** [comment]
Have quickly redesigned it @MyPickleCat  👍  Left you a voicemail to talk you through it but got cut off for talking too long haha! Anyway though you can get across the general sense of what I've done. Let me know what you think. If you're broadly happy with this then we'll carry on with this redesign

**Comment by thejoefriel** [comment]
> @thejoefriel and you can be in more than one section.
> I'd like to develop further after prototype that you can rank these areas. E.g. my services primarily addresses emotional wellness, but also offers social wellness - this way more 'score/match weighting' is given to emotional wellness.
> If a user was searching for emotional wellness, the above service would be shown in the listings above another service that ranks their number 1 priority as social wellness, followed by emotional wellness second.
> Think this is too sophisticated for prototype but tell me if I'm wrong!

Makes sense. For now we'll leave out ranking but will make sure people can select all the ones they feel they are relevant for.

**Comment by MyPickleCat** [comment]
@thejoefriel awesome, cheers!

**Comment by thejoefriel** [comment]
https://www.figma.com/proto/Y7kcZYebOHwyj34kBHasdhUU/myPickle?node-id=210%3A190&scaling=scale-down
